default_platform(:ios)

platform :ios do
  desc "Upload iOS metadata and binary"
  lane :upload_ios do |options|
    flavor = options[:flavor]
    app_id = JSON.parse(File.read('assets/flavors.json')).find { |f| f['flavorId'] == flavor }['appId']
    upload_to_app_store(
      username: ENV['APP_STORE_CONNECT_USERNAME'],
      app_identifier: app_id,
      ipa: "app/build/outputs/ipa/#{flavor}/Release/app.ipa",
      metadata_path: "fastlane/metadata/ios/#{flavor}",
      skip_screenshots: true,
      skip_metadata: false
    )
  end
end

platform :android do
  desc "Upload Android metadata and AAB"
  lane :upload_android do |options|
    flavor = options[:flavor]
    app_id = JSON.parse(File.read('assets/flavors.json')).find { |f| f['flavorId'] == flavor }['appId']
    supply(
      json_key: ENV['PLAY_STORE_SERVICE_ACCOUNT_JSON'],
      package_name: app_id,
      aab: "app/build/outputs/bundle/#{flavor}/Release/app.aab",
      metadata_path: "fastlane/metadata/android/#{flavor}",
      track: 'internal'
    )
  end
end
