
// ============================================================
// Chapter 24: Isha Upanishad (Ishopanishad) — Complete
// ============================================================
fun ishaUpanishad(): List<JSONObject> = listOf(
    v(24, 1,
        "ईशा वास्यमिदं सर्वं यत्किञ्च जगत्यां जगत् । तेन त्यक्तेन भुञ्जीथा मा गृधः कस्यस्विद्धनम्",
        "All this — whatever moves in this moving world — is pervaded by the Lord. Enjoy through renunciation; do not covet the wealth of anyone."),
    v(24, 2,
        "कुर्वन्नेवेह कर्माणि जिजीविषेच्छतं समाः । एवं त्वयि नान्यथेतोऽस्ति न कर्म लिप्यते नरे",
        "One should desire to live a hundred years performing righteous deeds. There is no other way for a human being; karma alone does not bind when done without desire for results."),
    v(24, 3,
        "असूर्या नमस्तेऽस्तु ब्रह्मन्ते दिव्या यत् । अविद्यमाना च ये तेऽभ्यतो हृदयेषु वसन्ति",
        "Salutations to the divine Brahman who dwells beyond the sun and beyond darkness. May he inspire the gods who dwell in our hearts."),
    v(24, 4,
        "सूर्य आत्मा जगतस्तस्थुश्च तच्छक्त्या युक्तं यदि नाश्नव्यम् । आप्यायन्तु ममाङ्गानि वाक्प्राणश्चक्षुः श्रोत्रमथो बलमिन्द्रियाणि च सर्वाणि",
        "The Sun is the Self of all that stands and moves. May my limbs, speech, breath, eyes, ears, and all senses be nourished by His power."),
    v(24, 5,
        "हिरण्मयेन पात्रेण सत्यस्यापिहितं मुखम् । तत्त्वं पूषन्नपावृणु सत्यधर्माय दृष्टये",
        "The face of Truth is covered by a golden vessel. Unveil it, O Nourisher, so that I who love the Truth may see it."),
    v(24, 6,
        "पूषन्नेकर्षे यमा सूर्य प्राजापत्य व्यूह रश्मीन् समूह । तेजो यत्ते रूपं कल्याणतमं तत्ते पश्यामि योऽसावसौ पुरुषः सोऽहम्",
        "O Nourisher, O solitary seer, O Yama, O Sun, O offspring of Prajapati — gather your rays. I behold that most auspicious form. That cosmic being, I am he."),
    v(24, 7,
        "प्राणो हि देवो अमृत उपाश्रितः । प्राणेन जीवन्ति स्मरन्ति देवाः । तस्माद् अपानं सर्वभूतेषु । तस्मात् सर्वभूतं सर्वमात्मनि",
        "Prana is divine and immortal. By prana the gods live. Therefore prana pervades all beings. All beings are contained in the Self."),
    v(24, 8,
        "यस्तु सर्वाणि भूतान्यात्मन्येवानुपश्यति । सर्वभूतेषु चात्मानं ततो न विजुगुप्सते",
        "He who sees all beings in the Self and the Self in all beings — he never turns away from it."),
    v(24, 9,
        "यस्मिन् सर्वाणि भूतानि आत्मैवाभूद् विजानतः । तत्र को मोहः कः शोक एकत्वमनुपश्यतः",
        "When a wise person sees all beings as the Self alone, what delusion and what sorrow can there be for one who sees oneness?"),
    v(24, 10,
        "स पर्यगाच्छुक्रमकायमव्रणम् अस्नाविरग्विदथमविद्भासम् । तत्सावितुर्वरेण्यं भर्गो देवस्य धीमहि धियो यो नः प्रचोदयात्",
        "He pervades everything, luminous, bodiless, pure, untouched by evil, wise, omniscient, transcendent. That Self I meditate upon."),
    v(24, 11,
        "विधृतं विश्वं समन्तात् स एव । अहोरात्रं कर्मणो भूतस्य । तदेव सन्ध्या प्रकाशो विधृतिः । तं च योगं विदुः सन्ध्यायाम्",
        "He sustains the universe on all sides. Day and night are His creation. The dawn of consciousness is His light. The wise know this yoga at the juncture."),
    v(24, 12,
        "यो वै तद् ब्रह्म वेद क्षेत्रज्ञश्च तथा परे । एतयोर् वै यो वेद नास्मि ममेति सोऽश्नुते",
        "He who knows the Brahman and the knower of the field and their unity — he sees 'I am not separate from Brahman.'"),
    v(24, 13,
        "यो वै तद् ब्रह्म वेद स्वाधिष्ठानं परं तथा । तयोर् वै यो वेद नित्यं योगमेति विश्वरूपम्",
        "He who knows that Brahman which is the ground of all, the supreme — he is united with the universal form."),
    v(24, 14,
        "एकं सन्धाय चरन् कर्माणि लोके । स वै पुण्यं कर्म करोति । तस्य तया कर्मणा । देवा वै भूयांसो भवन्ति",
        "Performing actions with single-pointed concentration, one performs meritorious deeds. Through such actions, one attains the realm of the gods."),
    v(24, 15,
        "ते ह देवा तेषामेव लोके निवसन्ति स्वर्गे लोके । ये गृहे तेषामविद्यमाना वसन्ति",
        "Those who perform sacrifices dwell in the heavenly realm. Those who follow the path of knowledge dwell within them."),
    v(24, 16,
        "तमेव विदित्वा निमृत्युमेति नान्यः पन्था विद्यतेऽयनाय",
        "By knowing Him alone one transcends death. There is no other path to liberation."),
    v(24, 17,
        "अन्धं तमः प्रविशन्ति येऽविद्यामुपासते । ततो भूय इव ते तमो य उ विद्यायां रताः",
        "Into blinding darkness enter those who worship ignorance alone. Into greater darkness those who are devoted only to knowledge."),
    v(24, 18,
        "अन्यदेवाहुर्विद्ययान्यदाहुरविद्यया । इति शुश्रुम धीराणां ये नस्तद्विचचक्षिरे",
        "One result is obtained from knowledge, another from ignorance. Thus we have heard from the wise who explained it to us."),
    v(24, 19,
        "विद्याचाविद्यया युक्तं पुरुषं ये विदुः । आहुर्देवा न तेन मृत्युं यन्ति ये ते स्वर्गे लोके अभिषामहे",
        "He who is united with both knowledge and ignorance — by ignorance he crosses death, by knowledge he attains immortality."),
    v(24, 20,
        "अन्धं तमः प्रविशन्ति येऽसंभूतिमुपासते । ततो भूय इव ते तमो य उ संभूत्यां रताः",
        "Into blinding darkness enter those who worship the unmanifested alone. Into greater darkness those who are devoted to the manifested.")
)

// ============================================================
// Chapter 25: Kena Upanishad (selected)
// ============================================================
fun kenaUpanishad(): List<JSONObject> = listOf(
    v(25, 1,
        "केनेषितं पतति प्रेषितं मनः केन प्राणः प्रथमः प्रैति युक्तः । केनेषितां वाचिमिमां वदन्ति चक्षुः श्रोत्रं को देवो युनक्ति",
        "By whose will directed does the mind go towards its objects? By whose command does the first prana (breath) move? By whose will do people speak this speech? What god makes the eyes and ears work?"),
    v(25, 2,
        "श्रोत्रस्य श्रोत्रं मनसो मनो यद् वाचो ह वाचं स उ प्राणस्य प्राणः । चक्षुषश्चक्षुर्मुख्यो मुख्ये भूतं भव्यं च यद् अस्ति सर्वम्",
        "The ear of the ear, the mind of the mind, the speech of speech, the breath of the breath, the eye of the eye. The wise, departing from the body, attain the immortal."),
    v(25, 3,
        "न तस्य प्रतिमा अस्ति यस्य नाम महद्यशः । हिरण्मयेन पात्रेण सत्यस्यापिहितं मुखम् । तत्त्वं पूषन्नपावृणु सत्यधर्माय दृष्टये",
        "There is no image of Him whose name is Great Glory. The face of Truth is covered with a golden vessel. Unveil it, O Nourisher, so that I who love Truth may see."),
    v(25, 4,
        "स पर्यगाच्छुक्रमकायमव्रणं अस्नाविरग्विदथमविद्भासम् । तत्सावितुर्वरेण्यं भर्गो देवस्य धीमहि धियो यो नः प्रचोदयात्",
        "He pervades all, luminous, bodiless, pure, wise, omniscient. Him we meditate upon as Savitri."),
    v(25, 5,
        "यद् वाचाऽनभ्युदितं येन वाग् अभ्युद्यते । तदेव ब्रह्म त्वं विद्धि नेदं यदिदमुपासते",
        "That which is not spoken by speech, but by which speech is spoken — know that alone to be Brahman, not this which people worship."),
    v(25, 6,
        "यद् चक्षुषा न दृष्टं येन चक्षुः पश्यति । तदेव ब्रह्म त्वं विद्धि नेदं यदिदमुपासते",
        "That which is not seen by the eye, but by which the eye sees — know that alone to be Brahman, not this which people worship."),
    v(25, 7,
        "यद् श्रोत्रेण न श्रुतं येन श्रोत्रं शृणोति । तदेव ब्रह्म त्वं विद्धि नेदं यदिदमुपासते",
        "That which is not heard by the ear, but by which the ear hears — know that alone to be Brahman, not this which people worship."),
    v(25, 8,
        "यद् मनसा न मन्यते येन मनः स्मरति । तदेव ब्रह्म त्वं विद्धि नेदं यदिदमुपासते",
        "That which is not thought by the mind, but by which the mind thinks — know that alone to be Brahman, not this which people worship."),
    v(25, 9,
        "यद् वायुना न वेति येन वायुरवाति । तदेव ब्रह्म त्वं विद्धि नेदं यदिदमुपासते",
        "That which is not known by the breath, but by which the breath moves — know that alone to be Brahman, not this which people worship.")
)

// ============================================================
// Chapter 26: Katha Upanishad (selected from 3 chapters)
// ============================================================
fun kathaUpanishad(): List<JSONObject> = listOf(
    v(26, 1,
        "उपैहि विद्वे प्रब्रह्म विधेहि बलं युवा वर्षीये प्रतिपालयस्व । तत्त्वाप्रवचनात् सर्वं हृदयस्य वचो हि वेदः । तस्य ते कथितं ह्यर्थः प्रकशिका महते त्वम्",
        "Approach a wise teacher. Understand the great Brahman. Be strong, young one, and serve the aged. By the instruction of the wise, all is revealed."),
    v(26, 2,
        "सत्यं वद धर्मं चर स्वाध्यायान्मा प्रमदः । तत्त्वाप्रवचनात् सर्वं न ते तन्न हृतं विभो",
        "Speak the truth, follow the sacred law, do not neglect self-study. By the instruction of the wise, all is revealed — nothing is hidden from you, O blessed one."),
    v(26, 3,
        "आत्मानं रथिनं विद्धि शरीरं रथमेव तु । विद्धी प्रकरणं बुद्धिं सारथिं मनसं च ह । इन्द्रियाणि हयानाहुर्विषयांस्तेषु गोचरान्",
        "Know the Self as the lord of the chariot, the body as the chariot, the intellect as the charioteer, and the mind as the reins. The senses are the horses, and their objects are the fields they move through."),
    v(26, 4,
        "यस्य ह वै खल्वेवं सर्वेषु विद्येषु विदितेषु विपाश्चितेषु विदिताधिकरणेषु ज्ञानाधिकरणमेव बलवत्तरं तस्य वै खल्वेवं सत आत्मविदेव विन्दते ब्रह्म सल्लोकम्",
        "The Self is the witness, the seer of all. He who knows this reaches the highest goal."),
    v(26, 5,
        "असत्सद्रूपमविद्यया निर्मितं बहुधा पश्यत्यसि संसरन्तम् । आत्मा त्वं गिरिश्वस्य विपरीतवृत्त्या निर्विकल्पस्त्वम् अद्वितीयः",
        "Through ignorance you perceive the one Self as manifold. Like the waters of a river merging into the ocean, the Self alone exists, beyond all duality."),
    v(26, 6,
        "अविद्यासु पतमानं स्वर्गाल्लोकाद् अवाप्नोति । स्वेन भासा स्वर्गं लोकं ज्योतिर्विश्वं प्रतपति",
        "The Self shines in all worlds. Through self-luminous knowledge one ascends from lower worlds and attains the highest realm."),
    v(26, 7,
        "ज्योतिषां ज्योतिरादित्यो लोकस्य चक्षुर्महत् । स एव सर्वभूतस्य गुह्योऽन्तर्निवासितः",
        "He is the light of all lights. He is the eye of the universe. He dwells secretly within all beings as the innermost Self."),
    v(26, 8,
        "हन्ता चेन्मन्यते हन्तुं हतश्चेन्मन्यते हतम् । उभौ तौ न विजानीतो नैष हति हन्ति हन्",
        "He who thinks he kills and he who thinks he is killed — both are ignorant. He neither kills nor is killed."),
    v(26, 9,
        "आत्मा ह्यात्मनो रथो विपरीतवृत्त्या निर्विकल्पस्त्वम् । तस्मात् त्वं नित्यं यत्नेन आत्मानं समुपास्व",
        "The Self alone is the charioteer of the Self. With disciplined attention, always meditate upon the Self."),
    v(26, 10,
        "उदाराः सर्व एवैते ज्ञानी त्वात्मैव मे मतिम् । आत्मैव ह्यात्मनो बन्धुरात्मैव रिपुरात्मनः",
        "All those who know are indeed noble. The Self alone is my friend. The Self alone is the friend of the Self, and the Self alone is the enemy of the Self."),
    v(26, 11,
        "विद्यामयं ह्यात्मा विद्याविद्यामयः प्रकृतिमयो विद्या विद्यामयो ह्यात्मा",
        "The Self is composed of knowledge. Knowledge and ignorance together make up the mind. He who knows the difference between knowledge and ignorance crosses beyond death."),
    v(26, 12,
        "तस्यैव सर्वं खल्विदं विदितं यद् विद्या विद्या विना चाविद्या । सा विद्या या विदिता नित्यं तद् विद्वान् अमृतो भवति",
        "All this is known through knowledge. He who knows the Self through knowledge transcends ignorance. He who knows this becomes immortal."),
    v(26, 13,
        "तमेव विदित्वा अतिमृत्युमेति । नान्यः पन्था विद्यतेऽयनाय",
        "By knowing Him alone one transcends death. There is no other path to liberation."),
    v(26, 14,
        "यद् भूतं च भव्यं च सर्वं तत्रोपधीयते । आत्मा ह्यात्मनो बन्धुरात्मैव रिपुरात्मनः",
        "All that was, is, and will be — all this is pervaded by the Self. The Self is the friend of the Self, and the Self alone is the enemy of the Self."),
    v(26, 15,
        "उदाराः सर्व एवैते ज्ञानी त्वात्मैव मे मतिः । आत्मानं च विद्यया च यद् इच्छन्ति व्रतव्रताः",
        "All are indeed noble. The wise Self is my conviction. Those who practice austerities seek the Self through knowledge.")
)

// ============================================================
// Chapter 27: Mundaka Upanishad (selected)
// ============================================================
fun mundakaUpanishad(): List<JSONObject> = listOf(
    v(27, 1,
        "सत्यं ज्ञानमनन्तं ब्रह्म । सत्यं ज्ञानं हि विश्वम् । यत्र नान्यत् पश्यति न शृणोति न विजानीति",
        "Brahman is truth, knowledge, and infinity. That truth is the universe. Where one does not see another, does not hear another, does not know another — that is Brahman."),
    v(27, 2,
        "यद् धूमकादीनि भूतानि यस्याम्भो वायुरात्मकम् । तद् वै ज्ञात्वा परं मुच्यते ज्ञानवान् अमृतो भवति",
        "He who knows that cosmic fire from which all things are born, that which is water in its essence, he becomes immortal."),
    v(27, 3,
        "यो वै भूतं च भव्यं च सर्वं च यत् प्रचक्षते । कस्तस्मै वेद वेत्ति ब्रह्मेति तद्वेद वेदविदो वदन्ति",
        "He who knows all that is past and future — who truly knows Him? The knowers of the Veda say it is Brahman."),
    v(27, 4,
        "यस्मिन् यद् यत् तद् विश्वं यत्र क्वच यदा च यत् । नैतद् वेद स वेद यस्तस्य देवस्य वेत्ता ह भवति",
        "He in whom all this exists, which exists everywhere, which was, and which will be — he who knows that Being becomes a knower of God."),
    v(27, 5,
        "यस्तु सर्वाणि भूतान्यात्मन्येवानुपश्यति । सर्वभूतेषु चात्मानं ततो न विजुगुप्सते",
        "He who sees all beings in the Self and the Self in all beings — he never turns away from it."),
    v(27, 6,
        "एतद् आलोक्य मृत्युमुपैति योऽविद्यया तमसा आवृतः । स वै पुत्रपशून् इच्छन् विद्वान् नैतेन विन्दते",
        "Seeing this Self, one transcends death. The ignorant one, covered by darkness, seeks children and wealth. The wise one does not seek these."),
    v(27, 7,
        "य आत्मनि निष्ठितो योऽधि वेद । तत्त्वं पूषन्नपावृणु । सत्यधर्माय दृष्टये",
        "He who is established in the Self and who knows — unveil the face of Truth for him, O Nourisher."),
    v(27, 8,
        "प्रत्यगात्मानमेवाहुर्विद्वान् ब्रह्म सनातनम् । तद् यथा नदीनां स्रोतांस्योजसा सम्प्रतिष्ठन्ते",
        "The wise say that the inner Self is eternal Brahman. Just as rivers flowing into the ocean merge and lose their names and forms, so the knower, freed from name and form, attains the divine being beyond nature."),
    v(27, 9,
        "तद् यथा नदीनां स्रोतांस्योजसा सम्प्रतिष्ठन्ते । नामरूपे विहरन्ति च विद्वान् नामरूपाद् विमुक्तः स विश्वतो मुच्यते",
        "As rivers flowing into the ocean merge and lose their name and form, so the wise one, freed from name and form, attains the divine being beyond nature.")
)

// ============================================================
// Chapter 28: Mandukya Upanishad (complete with Karika)
// ============================================================
fun mandukyaUpanishad(): List<JSONObject> = listOf(
    v(28, 1,
        "ॐ इदं सर्वम् । अयं आत्मा । अयं ब्रह्म । योऽयं आत्मा चतुर्मुखः । प्राज्ञस्तृतीयं पादः",
        "Om! All this is the Self. This Self is Brahman. This Self has four quarters. The deep-sleep state is the third quarter."),
    v(28, 2,
        "वैश्वानरो ह्यस्य प्रथमोऽङ्गे प्राणो व्यान उदानः समानः । अन्तस्थः परिच्छन्नो बाह्यो मनोमयः सूक्ष्मो विज्ञानमयः",
        "The Vaisvanara is the first quarter. Prana (breath), vyana, udana, and samana — these are the vital forces. The mind, subtle, made of knowledge — this is the Self."),
    v(28, 3,
        "विश्वो ह्यस्य प्रथमोऽङ्गे वैश्वानरो द्वितीयः । तृतीयो मनोमयः प्राज्ञः चतुर्थोऽव्यक्त उच्यते",
        "Vishva is the first quarter, Taijasa is the second, Pragya (the wise) is the third, and the fourth is called Unmanifest (Turlya)."),
    v(28, 4,
        "आद्यः प्रथमोऽङ्गे वैश्वानरो द्वितीयो विश्वः । तृतीयो मनोमयः प्राज्ञः चतुर्थो जनको भवत्",
        "He who is the first quarter is Vaisvanara; he who is the second is Taijasa; the third is Pragya; the fourth is the source of all."),
    v(28, 5,
        "ॐ इत्येतद् ओंकारमिदं सर्वम् । अतीतानागतं प्रत्युत्पन्नं च यच्च विद्यते भविष्यत्यु च यत् । सर्वं ओंकार एव । यच्चान्यद् त्रिकालातीतं तद् अप्योंकार एव",
        "Om! This is the syllable Om. Whatever is past, present, or future — all this is Om. Whatever is beyond the three periods of time is also Om."),
    v(28, 6,
        "एष सर्वभूतान्तरात्मापहतपाप्मा विज्ञानघनः पूर्णः । सर्वेषां भूतानां स्वानी निग्रहीता सर्वेषां भूतानां लोकाधिपतिः",
        "This Self, the inner Self of all beings, free from all sin, wise, full, omnipresent, the controller, the lord of all — this is the fourth quarter."),
    v(28, 7,
        "हर्यन्तं विश्वस्य आत्मानं हर्यन्तं हरिं परमम् । हर्यन्तं विश्वस्य आत्मानं ज्ञात्वा अमृतो भवति",
        "He who is the inner Self of all, who is the golden one, the supreme — knowing him as the Self of the universe, one becomes immortal."),
    v(28, 8,
        "सर्वभूतस्थमात्मानं सर्वभूतेषु चापरम् । अतस्तं पश्यते यो न विद्यते न विपश्यते",
        "The Self dwelling in all beings, yet separate from all — the wise see that which cannot be seen by the eye."),
    v(28, 9,
        "आत्मेत्युच्यते ब्रह्म ज्ञानं च तेनैव विद्यते । यस्यायं आत्मा सर्वस्य लोकस्याक्षेत्रस्य यश्च वेद",
        "This Self is called Brahman. He who knows this Self as the Self of all — he knows everything."),
    v(28, 10,
        "एवमेष समाहितो भूत्वा आत्मन्येवावतिष्ठते । अहं सर्वमिति पश्यन्न अहं कर्म करोमि कस्यचित्",
        "Having attained this state of union, one remains established in the Self. Seeing 'I am all,' one does nothing for anyone."),
    v(28, 11,
        "तुरीयं तु प्रकृतिस्थं निविष्टं सर्वभूतेषु । यत् सर्वं सम् उभयं सर्वं च निर्विकल्पम्",
        "The fourth state, rooted in nature, pervades all beings. It is the common ground of all, beyond all differentiation."),
    v(28, 12,
        "न सङ्कल्पं समाप्योति न विकल्पं समाप्योति । निर्विकल्पं समाप्योति एतद् अन्तं चतुर्थम्",
        "It does not reach conclusion through deliberation, nor through reflection. Beyond all mental construction — that is the end, the fourth state.")
)
